# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hasankatie/programming/my_repos/cpp_repos/shape-game-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hasankatie/programming/my_repos/cpp_repos/shape-game-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hasankatie/programming/my_repos/cpp_repos/shape-game-cpp/CMakeFiles /Users/hasankatie/programming/my_repos/cpp_repos/shape-game-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hasankatie/programming/my_repos/cpp_repos/shape-game-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shape_game_cpp

# Build rule for target.
shape_game_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shape_game_cpp
.PHONY : shape_game_cpp

# fast build rule for target.
shape_game_cpp/fast:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/build
.PHONY : shape_game_cpp/fast

Color.o: Color.cpp.o

.PHONY : Color.o

# target to build an object file
Color.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Color.cpp.o
.PHONY : Color.cpp.o

Color.i: Color.cpp.i

.PHONY : Color.i

# target to preprocess a source file
Color.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Color.cpp.i
.PHONY : Color.cpp.i

Color.s: Color.cpp.s

.PHONY : Color.s

# target to generate assembly for a file
Color.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Color.cpp.s
.PHONY : Color.cpp.s

Debug.o: Debug.cpp.o

.PHONY : Debug.o

# target to build an object file
Debug.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Debug.cpp.o
.PHONY : Debug.cpp.o

Debug.i: Debug.cpp.i

.PHONY : Debug.i

# target to preprocess a source file
Debug.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Debug.cpp.i
.PHONY : Debug.cpp.i

Debug.s: Debug.cpp.s

.PHONY : Debug.s

# target to generate assembly for a file
Debug.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Debug.cpp.s
.PHONY : Debug.cpp.s

Drawable.o: Drawable.cpp.o

.PHONY : Drawable.o

# target to build an object file
Drawable.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Drawable.cpp.o
.PHONY : Drawable.cpp.o

Drawable.i: Drawable.cpp.i

.PHONY : Drawable.i

# target to preprocess a source file
Drawable.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Drawable.cpp.i
.PHONY : Drawable.cpp.i

Drawable.s: Drawable.cpp.s

.PHONY : Drawable.s

# target to generate assembly for a file
Drawable.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Drawable.cpp.s
.PHONY : Drawable.cpp.s

FileUtil.o: FileUtil.cpp.o

.PHONY : FileUtil.o

# target to build an object file
FileUtil.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/FileUtil.cpp.o
.PHONY : FileUtil.cpp.o

FileUtil.i: FileUtil.cpp.i

.PHONY : FileUtil.i

# target to preprocess a source file
FileUtil.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/FileUtil.cpp.i
.PHONY : FileUtil.cpp.i

FileUtil.s: FileUtil.cpp.s

.PHONY : FileUtil.s

# target to generate assembly for a file
FileUtil.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/FileUtil.cpp.s
.PHONY : FileUtil.cpp.s

GLHandler.o: GLHandler.cpp.o

.PHONY : GLHandler.o

# target to build an object file
GLHandler.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/GLHandler.cpp.o
.PHONY : GLHandler.cpp.o

GLHandler.i: GLHandler.cpp.i

.PHONY : GLHandler.i

# target to preprocess a source file
GLHandler.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/GLHandler.cpp.i
.PHONY : GLHandler.cpp.i

GLHandler.s: GLHandler.cpp.s

.PHONY : GLHandler.s

# target to generate assembly for a file
GLHandler.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/GLHandler.cpp.s
.PHONY : GLHandler.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Game.cpp.s
.PHONY : Game.cpp.s

Globals.o: Globals.cpp.o

.PHONY : Globals.o

# target to build an object file
Globals.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Globals.cpp.o
.PHONY : Globals.cpp.o

Globals.i: Globals.cpp.i

.PHONY : Globals.i

# target to preprocess a source file
Globals.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Globals.cpp.i
.PHONY : Globals.cpp.i

Globals.s: Globals.cpp.s

.PHONY : Globals.s

# target to generate assembly for a file
Globals.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Globals.cpp.s
.PHONY : Globals.cpp.s

Input.o: Input.cpp.o

.PHONY : Input.o

# target to build an object file
Input.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Input.cpp.o
.PHONY : Input.cpp.o

Input.i: Input.cpp.i

.PHONY : Input.i

# target to preprocess a source file
Input.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Input.cpp.i
.PHONY : Input.cpp.i

Input.s: Input.cpp.s

.PHONY : Input.s

# target to generate assembly for a file
Input.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Input.cpp.s
.PHONY : Input.cpp.s

Object.o: Object.cpp.o

.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i

.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s

.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Object.cpp.s
.PHONY : Object.cpp.s

Position.o: Position.cpp.o

.PHONY : Position.o

# target to build an object file
Position.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Position.cpp.o
.PHONY : Position.cpp.o

Position.i: Position.cpp.i

.PHONY : Position.i

# target to preprocess a source file
Position.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Position.cpp.i
.PHONY : Position.cpp.i

Position.s: Position.cpp.s

.PHONY : Position.s

# target to generate assembly for a file
Position.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Position.cpp.s
.PHONY : Position.cpp.s

Rectangle.o: Rectangle.cpp.o

.PHONY : Rectangle.o

# target to build an object file
Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Rectangle.cpp.o
.PHONY : Rectangle.cpp.o

Rectangle.i: Rectangle.cpp.i

.PHONY : Rectangle.i

# target to preprocess a source file
Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Rectangle.cpp.i
.PHONY : Rectangle.cpp.i

Rectangle.s: Rectangle.cpp.s

.PHONY : Rectangle.s

# target to generate assembly for a file
Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Rectangle.cpp.s
.PHONY : Rectangle.cpp.s

RenderPackage.o: RenderPackage.cpp.o

.PHONY : RenderPackage.o

# target to build an object file
RenderPackage.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/RenderPackage.cpp.o
.PHONY : RenderPackage.cpp.o

RenderPackage.i: RenderPackage.cpp.i

.PHONY : RenderPackage.i

# target to preprocess a source file
RenderPackage.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/RenderPackage.cpp.i
.PHONY : RenderPackage.cpp.i

RenderPackage.s: RenderPackage.cpp.s

.PHONY : RenderPackage.s

# target to generate assembly for a file
RenderPackage.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/RenderPackage.cpp.s
.PHONY : RenderPackage.cpp.s

Scene.o: Scene.cpp.o

.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i

.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s

.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

ShaderHandler.o: ShaderHandler.cpp.o

.PHONY : ShaderHandler.o

# target to build an object file
ShaderHandler.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/ShaderHandler.cpp.o
.PHONY : ShaderHandler.cpp.o

ShaderHandler.i: ShaderHandler.cpp.i

.PHONY : ShaderHandler.i

# target to preprocess a source file
ShaderHandler.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/ShaderHandler.cpp.i
.PHONY : ShaderHandler.cpp.i

ShaderHandler.s: ShaderHandler.cpp.s

.PHONY : ShaderHandler.s

# target to generate assembly for a file
ShaderHandler.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/ShaderHandler.cpp.s
.PHONY : ShaderHandler.cpp.s

Shape.o: Shape.cpp.o

.PHONY : Shape.o

# target to build an object file
Shape.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Shape.cpp.o
.PHONY : Shape.cpp.o

Shape.i: Shape.cpp.i

.PHONY : Shape.i

# target to preprocess a source file
Shape.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Shape.cpp.i
.PHONY : Shape.cpp.i

Shape.s: Shape.cpp.s

.PHONY : Shape.s

# target to generate assembly for a file
Shape.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Shape.cpp.s
.PHONY : Shape.cpp.s

Timer.o: Timer.cpp.o

.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i

.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s

.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

Triangle.o: Triangle.cpp.o

.PHONY : Triangle.o

# target to build an object file
Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Triangle.cpp.o
.PHONY : Triangle.cpp.o

Triangle.i: Triangle.cpp.i

.PHONY : Triangle.i

# target to preprocess a source file
Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Triangle.cpp.i
.PHONY : Triangle.cpp.i

Triangle.s: Triangle.cpp.s

.PHONY : Triangle.s

# target to generate assembly for a file
Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Triangle.cpp.s
.PHONY : Triangle.cpp.s

VertexGenerator.o: VertexGenerator.cpp.o

.PHONY : VertexGenerator.o

# target to build an object file
VertexGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/VertexGenerator.cpp.o
.PHONY : VertexGenerator.cpp.o

VertexGenerator.i: VertexGenerator.cpp.i

.PHONY : VertexGenerator.i

# target to preprocess a source file
VertexGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/VertexGenerator.cpp.i
.PHONY : VertexGenerator.cpp.i

VertexGenerator.s: VertexGenerator.cpp.s

.PHONY : VertexGenerator.s

# target to generate assembly for a file
VertexGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/VertexGenerator.cpp.s
.PHONY : VertexGenerator.cpp.s

Window.o: Window.cpp.o

.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/Window.cpp.s
.PHONY : Window.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/shape_game_cpp.dir/build.make CMakeFiles/shape_game_cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... shape_game_cpp"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... Debug.o"
	@echo "... Debug.i"
	@echo "... Debug.s"
	@echo "... Drawable.o"
	@echo "... Drawable.i"
	@echo "... Drawable.s"
	@echo "... FileUtil.o"
	@echo "... FileUtil.i"
	@echo "... FileUtil.s"
	@echo "... GLHandler.o"
	@echo "... GLHandler.i"
	@echo "... GLHandler.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Globals.o"
	@echo "... Globals.i"
	@echo "... Globals.s"
	@echo "... Input.o"
	@echo "... Input.i"
	@echo "... Input.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Position.o"
	@echo "... Position.i"
	@echo "... Position.s"
	@echo "... Rectangle.o"
	@echo "... Rectangle.i"
	@echo "... Rectangle.s"
	@echo "... RenderPackage.o"
	@echo "... RenderPackage.i"
	@echo "... RenderPackage.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... ShaderHandler.o"
	@echo "... ShaderHandler.i"
	@echo "... ShaderHandler.s"
	@echo "... Shape.o"
	@echo "... Shape.i"
	@echo "... Shape.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... Triangle.o"
	@echo "... Triangle.i"
	@echo "... Triangle.s"
	@echo "... VertexGenerator.o"
	@echo "... VertexGenerator.i"
	@echo "... VertexGenerator.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

